# Make sure to check the documentation at http://goreleaser.com

# Snapcraft credentials
# snapcraft export-login --snaps=graphjin --channels=stable --acls=package_access,package_push,package_update,package_release credential

# GPG Key
# gpg --armor --export-secret-key <email> | pbcopy

before:
  hooks:
    - go mod download
    - make gen
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64

signs:
  - artifacts: checksum
    args:
      [
        "--batch",
        "-u",
        "{{ .Env.GPG_FINGERPRINT }}",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]

archives:

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch
      - go mod tidy

nfpms:
  - homepage: https://graphjin.com
    description: "Build APIs in 5 minutes. An automagical GraphQL to SQL compiler."
    license: Apache-2.0
    maintainer: Vikram Rangnekar (https://twitter.com/dosco)
    formats:
      - deb
      - rpm

brews:
  - tap:
      owner: dosco
      name: homebrew-graphjin
    folder: Formula
    homepage: https://graphjin.com
    description: "Build APIs in 5 minutes. An automagical GraphQL to SQL compiler."
    license: Apache-2.0
    skip_upload: auto

scoop:
  bucket:
    owner: dosco
    name: graphjin-scoop
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: https://graphjin.com
  description: "Build APIs in 5 minutes. An automagical GraphQL to SQL compiler."
  license: Apache-2.0

snapcrafts:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    summary: "Build APIs in 5 minutes. An automagical GraphQL to SQL compiler"
    description: |
      GraphJin gives you a high performance GraphQL API without you having to write any code. GraphQL is automagically compiled into an efficient SQL query. Use it either as a library or a standalone service.
    apps:
      graphjin:
        plugs: ["home", "network", "network-bind"]
    grade: stable
    confinement: strict
    publish: true
    license: Apache-2.0
    base: core18
