# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Graphjin < Formula
  desc "Build APIs in 5 minutes. An automagical GraphQL to SQL compiler."
  homepage "https://graphjin.com"
  version "0.15.88"
  license "Apache-2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/dosco/graphjin/releases/download/v0.15.88/graphjin_0.15.88_Darwin_x86_64.tar.gz"
    sha256 "acddf010f077c149b166b2052dba3915bc55d18e49891f127631ab50b730948d"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/dosco/graphjin/releases/download/v0.15.88/graphjin_0.15.88_Darwin_arm64.tar.gz"
    sha256 "9f647bd2471181dc8a4516757f00850998e50299cefac9a65c219b9c1fffb4ae"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/dosco/graphjin/releases/download/v0.15.88/graphjin_0.15.88_Linux_x86_64.tar.gz"
    sha256 "c979106d7f4282e8c48e87d7650ceb96ad6784a134fd0c16d11db830bf5c7e31"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/dosco/graphjin/releases/download/v0.15.88/graphjin_0.15.88_Linux_armv6.tar.gz"
    sha256 "f53b8f6465411794787276021a7e9a4efa335401bd3e8981a4f7f30e311e3075"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/dosco/graphjin/releases/download/v0.15.88/graphjin_0.15.88_Linux_arm64.tar.gz"
    sha256 "8b1fc4f1a258855e897d0e2adbb7f16d7ffd6d3a780074a0de8da77ec945da61"
  end

  def install
    bin.install "graphjin"
  end
end
