package redshift

import (
	"bufio"
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/dosco/graphjin/tests/v3/hostedemu"
)

const redshiftFixture = `
CREATE TABLE public.organizations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(1,1) PRIMARY KEY,
  name VARCHAR(120) SORTKEY ENCODE lzo NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
) DISTSTYLE ALL ENCODE AUTO;

CREATE TABLE public.users (
  id BIGINT IDENTITY(1,1) PRIMARY KEY,
  org_id INTEGER REFERENCES public.organizations(id),
  email VARCHAR(255) ENCODE lzo NOT NULL,
  profile SUPER,
  sketch HLLSKETCH,
  shape GEOMETRY,
  payload VARBYTE,
  disabled BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
) DISTSTYLE KEY DISTKEY(org_id) COMPOUND SORTKEY(created_at, id) ENCODE AUTO;
`

func TestParseSeedRedshiftDDL(t *testing.T) {
	schema, err := ParseSeedBytes([]byte(redshiftFixture))
	if err != nil {
		t.Fatal(err)
	}
	if len(schema.Tables) != 2 {
		t.Fatalf("tables = %d, want 2", len(schema.Tables))
	}

	users := schema.Table("public.users")
	if users == nil {
		t.Fatal("users table not parsed")
	}
	if users.DistStyle != "KEY" || users.DistKey != "org_id" {
		t.Fatalf("dist style/key = %q/%q, want KEY/org_id", users.DistStyle, users.DistKey)
	}
	if got := users.SortKeys; strings.Join(got, ",") != "created_at,id" {
		t.Fatalf("sort keys = %v, want [created_at id]", got)
	}

	id := users.Column("id")
	if id == nil || !id.Identity || !id.PrimaryKey || !id.NotNull {
		t.Fatalf("id column = %+v, want identity primary key not null", id)
	}
	orgID := users.Column("org_id")
	if orgID == nil || !orgID.DistKey || orgID.FKeyTable != "public.organizations" || orgID.FKeyColumn != "id" {
		t.Fatalf("org_id column = %+v, want distkey FK to organizations(id)", orgID)
	}
	email := users.Column("email")
	if email == nil || email.Encoding != "LZO" || !email.NotNull {
		t.Fatalf("email column = %+v, want LZO not null", email)
	}
	profile := users.Column("profile")
	if profile == nil || profile.Type != "SUPER" {
		t.Fatalf("profile column = %+v, want SUPER", profile)
	}

	orgs := schema.Table("organizations")
	if orgs == nil {
		t.Fatal("organizations table not parsed")
	}
	if orgs.DistStyle != "ALL" {
		t.Fatalf("organizations dist style = %q, want ALL", orgs.DistStyle)
	}
	orgPK := orgs.Column("id")
	if orgPK == nil || !orgPK.GeneratedIdentity || !orgPK.PrimaryKey {
		t.Fatalf("organizations id = %+v, want generated identity primary key", orgPK)
	}
}

func TestParseSeedRejectsPostgresOnlyDDL(t *testing.T) {
	tests := []struct {
		name string
		seed string
	}{
		{"json type", `CREATE TABLE bad (payload JSON);`},
		{"array type", `CREATE TABLE bad (tags VARCHAR[]);`},
		{"serial type", `CREATE TABLE bad (id SERIAL);`},
		{"index", `CREATE TABLE bad (id INT); CREATE INDEX bad_idx ON bad(id);`},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if _, err := ParseSeedBytes([]byte(tt.seed)); err == nil {
				t.Fatal("expected unsupported Redshift DDL error")
			}
		})
	}
}

func TestMapType(t *testing.T) {
	tests := map[string]string{
		"SUPER":                    "VARCHAR",
		"HLLSKETCH":                "VARCHAR",
		"GEOMETRY":                 "VARCHAR",
		"GEOGRAPHY":                "VARCHAR",
		"VARBYTE":                  "BLOB",
		"TIMESTAMPTZ":              "TIMESTAMP",
		"TIMESTAMP WITH TIME ZONE": "TIMESTAMP",
		"DOUBLE PRECISION":         "DOUBLE",
		"VARCHAR(255)":             "VARCHAR",
		"DECIMAL(10,2)":            "DECIMAL(10,2)",
	}
	for in, want := range tests {
		if got := MapType(in); got != want {
			t.Fatalf("MapType(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestTranslateSubscriptionUnbox(t *testing.T) {
	sql := `WITH _gj_sub AS (SELECT CAST(_gj_sub_unboxed.value[0] AS BIGINT) AS "id", CAST(_gj_sub_unboxed.value[1] AS VARCHAR) AS "cursor", _gj_sub_unboxed.idx AS "__gj_sub_order" FROM (SELECT JSON_PARSE(?) AS _gj_params) AS _gj_sub_input, UNNEST(_gj_sub_input._gj_params) WITH OFFSET AS _gj_sub_unboxed(value, idx)) SELECT (SELECT CAST(OBJECT_CONSTRUCT_KEEP_NULL('users', (SELECT OBJECT_CONSTRUCT_KEEP_NULL('id', "__sr_0"."id") AS "json" FROM (SELECT "users_0"."id" AS "id" FROM (SELECT "users"."id" FROM "public"."users" AS "users" WHERE (("users"."id") = "_gj_sub"."id") LIMIT 1) AS "users_0") AS "__sr_0")) AS VARCHAR) AS "__root" FROM ((SELECT true)) AS "__root_x") AS "__root" FROM _gj_sub ORDER BY "__gj_sub_order"`

	got := lowerRedshift(sql)
	for _, want := range []string{
		`json_each(CAST(? AS JSON))`,
		`CAST(json_extract(value, '$[0]') AS BIGINT) AS "id"`,
		`json_extract_string(value, '$[1]') AS "cursor"`,
		`CAST(key AS BIGINT) AS "__gj_sub_order"`,
		`json_object`,
		`ORDER BY "__gj_sub_order"`,
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("translated subscription SQL missing %q:\n%s", want, got)
		}
	}
	for _, disallowed := range []string{`JSON_PARSE`, `UNNEST`, `OBJECT_CONSTRUCT`, `"public".`} {
		if strings.Contains(got, disallowed) {
			t.Fatalf("translated subscription SQL should not contain %q:\n%s", disallowed, got)
		}
	}
}

func TestDirectDDLLowering(t *testing.T) {
	db := openRedshiftEmu(t, redshiftFixture, hostedemu.Config{
		Backend:  hostedemu.BackendDuckDB,
		Fallback: hostedemu.FallbackStrict,
	})
	defer db.Close()

	ddl := `
CREATE TABLE public.events (
  id BIGINT IDENTITY(1,1) PRIMARY KEY,
  payload SUPER,
  body VARCHAR ENCODE lzo,
  created_at TIMESTAMPTZ
) DISTSTYLE AUTO ENCODE AUTO COMPOUND SORTKEY(created_at, id);
`
	lowered := lowerRedshiftDirect(ddl)
	for _, bad := range []string{"IDENTITY", "DISTSTYLE", "ENCODE AUTO", "SORTKEY", "SUPER", "TIMESTAMPTZ"} {
		if strings.Contains(strings.ToUpper(lowered), bad) {
			t.Fatalf("lowered DDL still contains %q:\n%s", bad, lowered)
		}
	}

	if _, err := db.ExecContext(context.Background(), ddl); err != nil {
		t.Fatalf("exec Redshift DDL through simulator: %v", err)
	}

	var count int
	if err := db.QueryRowContext(context.Background(), `SELECT COUNT(*) FROM events`).Scan(&count); err != nil {
		t.Fatalf("query created table: %v", err)
	}
}

func TestDiscoverySurfaces(t *testing.T) {
	db := openRedshiftEmu(t, redshiftFixture, hostedemu.Config{
		Backend:  hostedemu.BackendDuckDB,
		Fallback: hostedemu.FallbackStrict,
	})
	defer db.Close()

	var tableName, distStyle string
	if err := db.QueryRowContext(context.Background(),
		`SHOW TABLES FROM SCHEMA dev.public LIKE 'users' LIMIT 1`,
	).Scan(new(string), new(string), &tableName, new(string), new(string), new(string), new(string), new(any), new(any), &distStyle, new(string)); err != nil {
		t.Fatal(err)
	}
	if tableName != "users" || distStyle != "KEY(org_id)" {
		t.Fatalf("SHOW TABLES row = %q/%q, want users/KEY(org_id)", tableName, distStyle)
	}

	rows, err := db.QueryContext(context.Background(), `SHOW COLUMNS FROM TABLE dev.public.users`)
	if err != nil {
		t.Fatal(err)
	}
	defer rows.Close()
	var sawEmail, sawOrgID bool
	for rows.Next() {
		var databaseName, schemaName, tableName, columnName, nullable, dataType, remarks, sortKeyType, encoding, collation string
		var ordinal int64
		var columnDefault sql.NullString
		var charMax, precision, scale sql.NullInt64
		var sortKey sql.NullInt64
		var distKey bool
		if err := rows.Scan(&databaseName, &schemaName, &tableName, &columnName, &ordinal, &columnDefault, &nullable, &dataType, &charMax, &precision, &scale, &remarks, &sortKeyType, &sortKey, &distKey, &encoding, &collation); err != nil {
			t.Fatal(err)
		}
		switch columnName {
		case "email":
			sawEmail = true
			if dataType != "character varying" || encoding != "lzo" || nullable != "NO" {
				t.Fatalf("email SHOW COLUMNS = type %q encoding %q nullable %q", dataType, encoding, nullable)
			}
		case "org_id":
			sawOrgID = true
			if !distKey {
				t.Fatal("org_id dist_key = false, want true")
			}
		}
	}
	if err := rows.Err(); err != nil {
		t.Fatal(err)
	}
	if !sawEmail || !sawOrgID {
		t.Fatalf("SHOW COLUMNS saw email=%t org_id=%t, want both", sawEmail, sawOrgID)
	}

	var dataType string
	var distKey bool
	if err := db.QueryRowContext(context.Background(),
		`SELECT data_type, dist_key FROM svv_all_columns WHERE table_name = 'users' AND column_name = 'org_id'`,
	).Scan(&dataType, &distKey); err != nil {
		t.Fatal(err)
	}
	if dataType != "integer" || !distKey {
		t.Fatalf("SVV_ALL_COLUMNS org_id = %q/%t, want integer/true", dataType, distKey)
	}

	var pgType, pgEncoding string
	var pgSortKey int64
	if err := db.QueryRowContext(context.Background(),
		`SELECT "type", encoding, sortkey FROM pg_table_def WHERE tablename = 'users' AND "column" = 'created_at'`,
	).Scan(&pgType, &pgEncoding, &pgSortKey); err != nil {
		t.Fatal(err)
	}
	if pgType != "timestamptz" || pgEncoding != "raw" || pgSortKey != 1 {
		t.Fatalf("PG_TABLE_DEF created_at = %q/%q/%d, want timestamptz/raw/1", pgType, pgEncoding, pgSortKey)
	}
}

func TestDefaultFixtureBootsDuckDB(t *testing.T) {
	db := sql.OpenDB(hostedemu.NewConnector(hostedemu.Config{
		SeedPath: filepath.Join("..", "..", "redshift.sql"),
		Backend:  hostedemu.BackendDuckDB,
		Fallback: hostedemu.FallbackStrict,
		TestName: "redshift-default-fixture",
		RunID:    "unit",
	}, NewAdapter()))
	defer db.Close()

	var tableName string
	if err := db.QueryRowContext(context.Background(),
		`SHOW TABLES FROM SCHEMA dev.public LIKE 'users'`,
	).Scan(new(string), new(string), &tableName, new(string), new(string), new(string), new(string), new(any), new(any), new(string), new(string)); err != nil {
		t.Fatal(err)
	}
	if tableName != "users" {
		t.Fatalf("SHOW TABLES table_name = %q, want users", tableName)
	}
}

func TestDiscoveryUsesBatchMetadataForLargeCatalog(t *testing.T) {
	const tableCount = 5000

	dir := t.TempDir()
	captureDir := filepath.Join(dir, "capture")
	db := openRedshiftEmu(t, scaleSeed(tableCount), hostedemu.Config{
		CaptureDir: captureDir,
		TestName:   "redshift-discovery-scale",
		Backend:    hostedemu.BackendDuckDB,
		Fallback:   hostedemu.FallbackStrict,
	})
	defer db.Close()

	rows, err := db.QueryContext(context.Background(), `SHOW TABLES FROM SCHEMA dev.public`)
	if err != nil {
		t.Fatal(err)
	}
	var tables int
	for rows.Next() {
		tables++
	}
	if err := rows.Close(); err != nil {
		t.Fatal(err)
	}
	if tables != tableCount {
		t.Fatalf("SHOW TABLES rows = %d, want %d", tables, tableCount)
	}

	var cols int
	if err := db.QueryRowContext(context.Background(),
		`SELECT COUNT(*) FROM svv_all_columns WHERE table_name LIKE 'scale_table_%'`,
	).Scan(&cols); err != nil {
		t.Fatal(err)
	}
	if cols != tableCount*2 {
		t.Fatalf("SVV_ALL_COLUMNS scale columns = %d, want %d", cols, tableCount*2)
	}

	events, err := readCaptureEvents(hostedemu.CapturePath(captureDir, "redshift-discovery-scale"))
	if err != nil {
		t.Fatal(err)
	}
	var discoveryQueries int
	perTableShow := regexp.MustCompile(`(?i)^SHOW COLUMNS FROM TABLE .*scale_table_[0-9]{4}`)
	for _, ev := range events {
		if ev.Phase != "discovery" || ev.Op != "query" {
			continue
		}
		discoveryQueries++
		if perTableShow.MatchString(ev.NormalizedSQL) {
			t.Fatalf("per-table SHOW COLUMNS query detected: %s", ev.NormalizedSQL)
		}
	}
	if discoveryQueries > 2 {
		t.Fatalf("discovery query count = %d, want <= 2", discoveryQueries)
	}
}

func openRedshiftEmu(t *testing.T, seed string, conf hostedemu.Config) *sql.DB {
	t.Helper()
	dir := t.TempDir()
	seedPath := filepath.Join(dir, "redshift.sql")
	if err := os.WriteFile(seedPath, []byte(seed), 0644); err != nil {
		t.Fatal(err)
	}
	conf.SeedPath = seedPath
	if conf.TestName == "" {
		conf.TestName = "redshift-test"
	}
	db := sql.OpenDB(hostedemu.NewConnector(conf, NewAdapter()))
	if err := db.PingContext(context.Background()); err != nil {
		_ = db.Close()
		t.Fatal(err)
	}
	return db
}

func scaleSeed(n int) string {
	var b strings.Builder
	for i := 1; i <= n; i++ {
		fmt.Fprintf(&b, "CREATE TABLE scale_table_%04d (id BIGINT IDENTITY(1,1) PRIMARY KEY, name VARCHAR(120) ENCODE lzo) DISTSTYLE EVEN;\n", i)
	}
	return b.String()
}

type captureLine struct {
	Op            string `json:"op"`
	Phase         string `json:"phase"`
	NormalizedSQL string `json:"normalized_sql"`
}

func readCaptureEvents(path string) ([]captureLine, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var out []captureLine
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		var ev captureLine
		if err := json.Unmarshal(sc.Bytes(), &ev); err != nil {
			return nil, err
		}
		out = append(out, ev)
	}
	return out, sc.Err()
}
