CREATE TABLE public.organizations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(1,1) PRIMARY KEY,
  name VARCHAR(120) SORTKEY ENCODE lzo NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
) DISTSTYLE ALL ENCODE AUTO;

CREATE TABLE public.users (
  id BIGINT IDENTITY(1,1) PRIMARY KEY,
  org_id INTEGER REFERENCES public.organizations(id),
  email VARCHAR(255) ENCODE lzo NOT NULL,
  phone VARCHAR(32),
  profile SUPER,
  sketch HLLSKETCH,
  shape GEOMETRY,
  payload VARBYTE,
  disabled BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
) DISTSTYLE KEY DISTKEY(org_id) COMPOUND SORTKEY(created_at, id) ENCODE AUTO;

CREATE TABLE public.events (
  id BIGINT IDENTITY(1,1),
  user_id BIGINT NOT NULL,
  metadata SUPER,
  amount DECIMAL(10,2),
  occurred_at TIMESTAMP WITHOUT TIME ZONE,
  FOREIGN KEY(user_id) REFERENCES public.users(id)
) DISTSTYLE EVEN INTERLEAVED SORTKEY(user_id, occurred_at);

CREATE TABLE public.chats (
  id BIGINT PRIMARY KEY,
  body VARCHAR(255) ENCODE lzo NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) DISTSTYLE AUTO COMPOUND SORTKEY(id) ENCODE AUTO;

INSERT INTO public.organizations (id, name, created_at) VALUES
  (1, 'GraphJin Labs', '2024-01-01 00:00:00+00');

INSERT INTO public.users (id, org_id, email, phone, profile, sketch, shape, payload, disabled, created_at) VALUES
  (1, 1, 'ada@example.com', NULL, JSON_PARSE('{"tier":"pro"}'), '{"hll":"mock"}', 'POINT(0 0)', '616263', FALSE, '2024-01-02 00:00:00+00'),
  (2, 1, 'grace@example.com', NULL, JSON_PARSE('{"tier":"team"}'), '{"hll":"mock"}', 'POINT(1 1)', '646566', FALSE, '2024-01-02 00:00:00+00');

INSERT INTO public.events (id, user_id, metadata, amount, occurred_at) VALUES
  (1, 1, JSON_PARSE('{"kind":"login"}'), 12.50, '2024-01-03 00:00:00');

INSERT INTO public.chats (id, body, created_at) VALUES
  (1, 'This is chat message number 1', '2024-01-04 00:00:00'),
  (2, 'This is chat message number 2', '2024-01-04 00:00:01'),
  (3, 'This is chat message number 3', '2024-01-04 00:00:02');
