// Package auth provides an API to use GraphJin serv auth handles with your own application. Works with routers like chi and http mux.
// For detailed documentation visit https://graphjin.com
//
// Example usage:
/*
	package main

	import (
		"net/http"
		"path/filepath"
		"github.com/go-chi/chi"
		"github.com/dosco/graphjin/serv/v3"
		"github.com/dosco/graphjin/auth/v3"
	)

	func main() {
		conf, err := serv.ReadInConfig(filepath.Join("./config", serv.GetConfigName()))
		if err != nil {
			panic(err)
		}

		useAuth, err := auth.NewAuth(conf.Auth, log, auth.Options{AuthFailBlock: true})
		if err != nil {
			panic(err)
		}

		r := chi.NewRouter()
		r.Use(useAuth)
		r.Get("/user", userInfo)

		http.ListenAndServe(":8080", r)
	}
*/
package auth

import (
	"context"
	"crypto/subtle"
	"errors"
	"fmt"
	"net/http"
	"strconv"
	"strings"

	"github.com/dosco/graphjin/core/v3"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"

	"github.com/dosco/graphjin/auth/v3/provider"
)

type JWTConfig = provider.JWTConfig

// Auth struct contains authentication related config values used by the GraphJin service
type Auth struct {
	// Enable development mode used to set credentials in the header and vars for testing
	Development bool `jsonschema:"title=Development Mode,default=false"`

	// Name is a friendly name for this auth config
	Name string

	// Type can be one of jwt or header
	Type string `jsonschema:"title=Type,enum=jwt,enum=header"`

	// The name of the cookie that holds the authentication token
	Cookie string `jsonschema:"title=Cookie Name"`

	// In certain cases like Magiclink the jwt cookie is generated by us this
	// set the secure parameter of this cookie
	// CookieHTTPS bool `mapstructure:"cookie_https"`

	// In certain cases like Magiclink the jwt cookie is generated by us this
	// set the expiry parameter of this cookie (ex. "20m", "2h")
	// CookieExpiry string `mapstructure:"cookie_expiry"`

	// JWT authentication
	JWT JWTConfig

	// Header authentication
	Header struct {
		// Name of the HTTP header
		Name string

		// Value if set must match expected value (optional)
		Value string

		// Exists if set to true then the header must exist
		// this is an alternative to using value
		Exists bool
	}

	// Magic.link authentication
	// MagicLink struct {
	// 	Secret string
	// }
}

type HandlerFunc func(w http.ResponseWriter, r *http.Request) (context.Context, error)

// authCtxKey is a private context-key type used to stash optional identity
// claims (email, name) on the request context for audit logging. Read-back
// is via UserEmail / UserName below.
type authCtxKey int

const (
	userEmailKey authCtxKey = iota
	userNameKey
	userClaimsKey
)

// UserEmail returns the verified email claim attached to ctx by JwtHandler,
// or "" if absent.
func UserEmail(ctx context.Context) string {
	if ctx == nil {
		return ""
	}
	v, _ := ctx.Value(userEmailKey).(string)
	return v
}

// UserName returns the verified name claim attached to ctx by JwtHandler,
// or "" if absent.
func UserName(ctx context.Context) string {
	if ctx == nil {
		return ""
	}
	v, _ := ctx.Value(userNameKey).(string)
	return v
}

// UserClaims returns a shallow copy of verified JWT claims attached to ctx by
// JwtHandler. Raw tokens are never stored here.
func UserClaims(ctx context.Context) map[string]interface{} {
	if ctx == nil {
		return nil
	}
	claims, _ := ctx.Value(userClaimsKey).(map[string]interface{})
	if claims == nil {
		return nil
	}
	out := make(map[string]interface{}, len(claims))
	for k, v := range claims {
		out[k] = v
	}
	return out
}

type Options struct {
	// Return a HTTP '401 Unauthoized' when auth fails
	AuthFailBlock bool
}

// NewAuthHandlerFunc returns a HandlerFunc based on the provided config.
// Usually you don't need to use this function, because is called by NewAuth if
// no HandlerFunc is provided.
func NewAuthHandlerFunc(ac Auth) (HandlerFunc, error) {
	var h HandlerFunc
	var err error

	switch ac.Development {
	case true:
		h, err = SimpleHandler(ac)

	default:
		switch ac.Type {
		case "jwt":
			h, err = JwtHandler(ac)

		case "header":
			h, err = HeaderHandler(ac)

		// case "magiclink":
		// 	h, err = MagicLinkHandler(ac, next)

		case "", "none":
			h, err = NoAuth()

		default:
			return nil, fmt.Errorf("auth: unknown auth type: %s", ac.Type)
		}

		if err != nil {
			return nil, fmt.Errorf("%s: %s", ac.Type, err.Error())
		}
	}
	return h, err
}

// NoAuth returns a handler that does not perform any authentication.
func NoAuth() (HandlerFunc, error) {
	return func(w http.ResponseWriter, r *http.Request) (context.Context, error) {
		return r.Context(), nil
	}, nil
}

// NewAuth returns a new auth handler. It will create a HandlerFunc based on the
// provided config.
//
// Optionally an existing HandlerFunc can be provided. This is required to
// support auth in WS subscriptions.
func NewAuth(ac Auth, log *zap.Logger, opt Options, hFn ...HandlerFunc) (
	func(next http.Handler) http.Handler, error,
) {
	var err error
	var h HandlerFunc
	var wsAuthSupported bool

	if len(hFn) != 0 && hFn[0] != nil {
		h = hFn[0]
		wsAuthSupported = true
	} else {
		h, err = NewAuthHandlerFunc(ac)
		if err != nil {
			return nil, err
		}
	}

	return func(next http.Handler) http.Handler {
		ah := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if wsAuthSupported && isWebSocketUpgrade(r) {
				next.ServeHTTP(w, r)
				return
			}
			c, err := h(w, r)
			if err != nil && log != nil {
				log.Error("Auth", []zapcore.Field{zap.String("type", ac.Type), zap.Error(err)}...)
			}

			if err == Err401 {
				http.Error(w, "401 unauthorized", http.StatusUnauthorized)
				return
			}

			if opt.AuthFailBlock && !IsAuth(c) {
				http.Error(w, "401 unauthorized", http.StatusUnauthorized)
				return
			}

			// Audit log: emit a single structured line per authenticated
			// request when we have identity beyond just `sub`. Skipped on
			// dev-mode handlers and unauthenticated requests.
			if err == nil && c != nil && log != nil {
				logAuthAudit(log, c, ac.Type, r)
			}

			if c != nil {
				next.ServeHTTP(w, r.WithContext(c))
			} else {
				next.ServeHTTP(w, r)
			}
		})

		return ah
	}, nil
}

// SimpleHandler is a simple auth handler that sets the user ID, provider and role
func SimpleHandler(ac Auth) (HandlerFunc, error) {
	return func(_ http.ResponseWriter, r *http.Request) (context.Context, error) {
		c := r.Context()

		userIDProvider := r.Header.Get("X-User-ID-Provider")
		if userIDProvider != "" {
			c = context.WithValue(c, core.UserIDProviderKey, userIDProvider)
		}

		userID := r.Header.Get("X-User-ID")
		if userID != "" {
			c = context.WithValue(c, core.UserIDKey, userID)
		}

		userRole := r.Header.Get("X-User-Role")
		if userRole != "" {
			c = context.WithValue(c, core.UserRoleKey, userRole)
			c = context.WithValue(c, core.IdentityRolesKey, []string{userRole})
		}

		accountID := r.Header.Get("X-Account-ID")
		if accountID != "" {
			c = context.WithValue(c, core.IdentityVarsKey, map[string]interface{}{"account_id": accountID})
		}

		return c, nil
	}, nil
}

var Err401 = errors.New("401 unauthorized")

// logAuthAudit emits one structured log line per authenticated request,
// recording the verified identity claims so audit trails can answer "who
// called this endpoint." Only fields that were actually present on the JWT
// are emitted — never invent or leak missing claims.
func logAuthAudit(log *zap.Logger, ctx context.Context, authType string, r *http.Request) {
	uid := UserID(ctx)
	email := UserEmail(ctx)
	name := UserName(ctx)
	if uid == nil && email == "" && name == "" {
		return
	}
	fields := []zapcore.Field{
		zap.String("auth_type", authType),
		zap.String("method", r.Method),
		zap.String("path", r.URL.Path),
	}
	if uid != nil {
		fields = append(fields, zap.Any("user_id", uid))
	}
	if email != "" {
		fields = append(fields, zap.String("email", email))
	}
	if name != "" {
		fields = append(fields, zap.String("name", name))
	}
	log.Info("auth.request", fields...)
}

// HeaderHandler is a middleware that checks for a header value
func HeaderHandler(ac Auth) (HandlerFunc, error) {
	hdr := ac.Header

	if hdr.Name == "" {
		return nil, fmt.Errorf("auth '%s': no header.name defined", ac.Name)
	}

	if !hdr.Exists && hdr.Value == "" {
		return nil, fmt.Errorf("auth '%s': no header.value defined", ac.Name)
	}

	return func(_ http.ResponseWriter, r *http.Request) (context.Context, error) {
		var fo1 bool
		value := r.Header.Get(hdr.Name)

		switch {
		case hdr.Exists:
			fo1 = (value == "")

		default:
			fo1 = (subtle.ConstantTimeCompare([]byte(value), []byte(hdr.Value)) != 1)
		}

		if fo1 {
			return nil, Err401
		}
		return nil, nil
	}, nil
}

// IsAuth returns true if the context contains a user ID
func IsAuth(c context.Context) bool {
	return c != nil && c.Value(core.UserIDKey) != nil
}

// UserID returns the user ID from the context
func UserID(c context.Context) interface{} {
	return c.Value(core.UserIDKey)
}

// UserIDInt returns the user ID from the context as an int
func UserIDInt(c context.Context) int {
	v, ok := UserID(c).(string)
	if !ok {
		return -1
	}
	if v, err := strconv.Atoi(v); err == nil {
		return v
	}
	return -1
}

// isWebSocketUpgrade reports whether r is a WebSocket upgrade request.
func isWebSocketUpgrade(r *http.Request) bool {
	if r.Header.Get("Upgrade") == "" {
		return false
	}
	if !strings.EqualFold(r.Header.Get("Upgrade"), "websocket") {
		return false
	}
	return strings.Contains(strings.ToLower(r.Header.Get("Connection")), "upgrade")
}
