# Inherit config from this other config file
# so I only need to overwrite some values
inherits: dev

app_name: "{% app_name %} Production"
host_port: 0.0.0.0:8080
web_ui: false

# debug, info, warn, error, fatal, panic, disable
log_level: "warn"

# enable or disable http compression (uses gzip)
http_compress: true

# When production mode is 'true' only queries 
# from the allow list are permitted.
# When it's 'false' all queries are saved to the
# the allow list in ./config/allow.list
production: true

# Throw a 401 on auth failure for queries that need auth
auth_fail_block: true

# Latency tracing for database queries and remote joins
# the resulting latency information is returned with the
# response
enable_tracing: true

# File that points to the database seeding script
# seed_file: seed.js

# Path pointing to where the migrations can be found
# migrations_path: migrations

# Secret key for general encryption operations like 
# encrypting the cursor data
# secret_key: supercalifajalistics

# Postgres related environment Variables
# SG_DATABASE_HOST
# SG_DATABASE_PORT
# SG_DATABASE_USER
# SG_DATABASE_PASSWORD

# Auth related environment Variables
# SG_AUTH_RAILS_COOKIE_SECRET_KEY_BASE
# SG_AUTH_RAILS_REDIS_URL
# SG_AUTH_RAILS_REDIS_PASSWORD
# SG_AUTH_JWT_PUBLIC_KEY_FILE

database:
  type: postgres
  host: db
  port: 5432
  dbname: {% app_name_slug %}_development
  user: postgres
  password: postgres
  #pool_size: 10
  #max_retries: 0
  #log_level: "debug" 

  # Set session variable "user.id" to the user id
  # Enable this if you need the user id in triggers, etc
  set_user_id: false

  # database ping timeout is used for db health checking
  ping_timeout: 5m