package main

import (
	"fmt"
	"path/filepath"
	"strconv"
	"strings"

	gjeval "github.com/dosco/graphjin/agent/v3/eval"
)

// Choosing what a served environment asks, and what it asks it of.
//
// A container that has to be handed a suite file is a container somebody has
// to build a world for first. The binary already carries the frozen public
// suite; letting the server reach it is what makes an image that boots ready
// with nothing mounted.

// envSuiteEmbedded is the reserved word selecting the built-in suite. Reserved
// rather than a separate boolean flag: one selector slot means one environment
// variable, which is the whole point in a container. A file genuinely named
// "public" is still reachable as "./public".
const envSuiteEmbedded = "public"

// defaultAutoSplitRatio matches `eval create --split 0.8`, so a file-free
// holdout divides the same way the documented one does.
const defaultAutoSplitRatio = 0.8

// resolveEnvSuite loads the suite a server will serve, and says where it came
// from.
func resolveEnvSuite(spec string) (gjeval.Suite, string, error) {
	trimmed := strings.TrimSpace(spec)
	if strings.EqualFold(trimmed, envSuiteEmbedded) {
		suite, err := loadPublicEvalSuite()
		if err != nil {
			return gjeval.Suite{}, "", err
		}
		if err := assertServableSuite(*suite); err != nil {
			return gjeval.Suite{}, "", err
		}
		return *suite, envSuiteEmbedded, nil
	}
	suite, err := gjeval.LoadSuite(trimmed)
	if err != nil {
		return gjeval.Suite{}, "", fmt.Errorf("load suite: %w", err)
	}
	if err := assertServableSuite(*suite); err != nil {
		return gjeval.Suite{}, "", err
	}
	return *suite, trimmed, nil
}

// assertServableSuite refuses a suite this binary cannot grade.
//
// LoadSuite already checks this; the embedded loader does not, and a suite
// whose generator this binary does not know would be scored under rules that
// were never written for it.
func assertServableSuite(suite gjeval.Suite) error {
	if !gjeval.IsSupportedGeneratorVersion(suite.Generator.Version) {
		return fmt.Errorf(
			"suite was generated by %s, which this binary cannot run; regenerate it with `graphjin eval create`",
			suite.Generator.Version)
	}
	if len(suite.Tasks) == 0 {
		return fmt.Errorf("suite contains no tasks")
	}
	return nil
}

// resolveEnvSplit decides which holdout a server enforces.
//
// "auto" derives one from the suite itself: sides come from each task's content
// id, so two containers started from one image agree on the division with
// nothing mounted and no coordination between them.
func resolveEnvSplit(spec string, suite gjeval.Suite) (*gjeval.SuiteSplit, string, error) {
	trimmed := strings.TrimSpace(spec)
	switch {
	case trimmed == "":
		return nil, "none", nil
	case trimmed == "auto" || strings.HasPrefix(trimmed, "auto:"):
		ratio := defaultAutoSplitRatio
		if _, raw, found := strings.Cut(trimmed, ":"); found {
			parsed, err := strconv.ParseFloat(strings.TrimSpace(raw), 64)
			if err != nil {
				return nil, "", fmt.Errorf("--split auto:<ratio> needs a number, got %q", raw)
			}
			if parsed <= 0 || parsed >= 1 {
				return nil, "", fmt.Errorf("--split auto:<ratio> must be between 0 and 1, got %v", parsed)
			}
			ratio = parsed
		}
		split, err := gjeval.SplitSuite(suite, ratio, nil)
		if err != nil {
			return nil, "", err
		}
		return &split, fmt.Sprintf("auto:%.2f", ratio), nil
	default:
		split, err := gjeval.LoadSplit(trimmed)
		if err != nil {
			return nil, "", fmt.Errorf("load split: %w", err)
		}
		// The same guard `eval sample` and `eval export` apply, and which this
		// path has been missing: a split cut from another suite names task ids
		// that do not exist here, so it would silently hold out nothing.
		if want := gjeval.SuiteFingerprint(suite); split.SuiteFingerprint != "" && split.SuiteFingerprint != want {
			return nil, "", fmt.Errorf(
				"%s was cut from a different suite (%s) than the one being served (%s)",
				trimmed, split.SuiteFingerprint, want)
		}
		return split, "file:" + filepath.Base(trimmed), nil
	}
}

// assertSuiteMatchesWorld refuses to serve questions verified against a
// different database.
//
// Every task's oracle was resolved against the catalog the suite records. Point
// the same suite at a world whose schema has moved and the oracles describe
// something else — the episodes still run, still score, and mean nothing. The
// comparison existed only in a test until now.
func assertSuiteMatchesWorld(suite gjeval.Suite, world gjeval.DatasetFingerprint, allowDrift bool) error {
	if suite.CatalogFingerprint == "" || world.CatalogHash == "" {
		return nil
	}
	if suite.CatalogFingerprint == world.CatalogHash {
		return nil
	}
	if allowDrift {
		return nil
	}
	return fmt.Errorf(
		"this suite was verified against catalog %s but the world serves %s; its oracles do not describe "+
			"this database, so every episode would be graded against the wrong answer. Regenerate with "+
			"`graphjin eval create`, or pass --allow-catalog-drift if you know better",
		suite.CatalogFingerprint, world.CatalogHash)
}

// catalogAgreement reports whether the suite is being served on the world it
// was verified against, or nil when there is nothing to compare.
//
// A suite with no recorded catalog is not a match and not a mismatch, and
// flattening that to false would read as drift that was never detected.
func catalogAgreement(suite gjeval.Suite, world gjeval.DatasetFingerprint) *bool {
	if suite.CatalogFingerprint == "" || world.CatalogHash == "" {
		return nil
	}
	match := suite.CatalogFingerprint == world.CatalogHash
	return &match
}
